### ISSUE TITLE
doesnt play nice with github dark theme

### ISSUE THREAD

**Issue by Kaminate** [KadaB/axis_angle_rotation#2]
![dark theme](https://user-images.githubusercontent.com/1840482/149703660-371d44fa-ca00-458d-8898-9815d9968298.png)

**Comment by KadaB** [comment]
Oh wow, true. Didn't anticipate that .... Thx for the feedback. You can still look at the PDF, can you?

**Comment by KadaB** [comment]
Ok, I uploaded a version with white background color. Thx for the feedback.
